-- MySQL Script generated by MySQL Workbench
-- Wed Aug 23 15:30:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema theatertickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema theatertickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `theatertickets` DEFAULT CHARACTER SET utf8 ;
USE `theatertickets` ;

-- -----------------------------------------------------
-- Table `theatertickets`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theatertickets`.`user` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(16) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(32) NOT NULL,
  `user_tickets` VARCHAR(250) NULL,
  UNIQUE INDEX `email_UNIQUE` (`user_email` ASC) VISIBLE,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `theatertickets`.`production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theatertickets`.`production` (
  `production_id` INT NOT NULL AUTO_INCREMENT,
  `production_name` VARCHAR(45) NOT NULL,
  `production_description` VARCHAR(250) NOT NULL DEFAULT 'Lorem Ipsum',
  `production_duration` INT NOT NULL DEFAULT 60,
  `production_tags` VARCHAR(200) NULL,
  PRIMARY KEY (`production_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theatertickets`.`event_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theatertickets`.`event_detail` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `production_id` INT NOT NULL,
  `event_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `event_capacity` INT NOT NULL DEFAULT 100,
  `event_tksold` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`event_id`),
  INDEX `production_id_idx` (`production_id` ASC) VISIBLE,
  CONSTRAINT `production_id`
    FOREIGN KEY (`production_id`)
    REFERENCES `theatertickets`.`production` (`production_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `theatertickets`.`ticket_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theatertickets`.`ticket_detail` (
  `ticket_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  `event_detail_id` INT NOT NULL,
  `ticket_state` INT NOT NULL,
  PRIMARY KEY (`ticket_id`, `user_user_id`, `event_detail_id`),
  INDEX `fk_user_has_event_user_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_user_has_event_event1_idx` (`event_detail_id` ASC) VISIBLE,
  UNIQUE INDEX `ticket_id_UNIQUE` (`ticket_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_event_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `theatertickets`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_event_event1`
    FOREIGN KEY (`event_detail_id`)
    REFERENCES `theatertickets`.`event_detail` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
